//
// Nutritions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Nutritions: Codable, JSONEncodable, Hashable {

    /** Carbohydrates of the Fruit (per 100g) in gramm. */
    public var carbohydrates: Double?
    /** Protein of the Fruit (per 100g) in gramm. */
    public var protein: Double?
    /** Fat of the Fruit (per 100g) in gramm. */
    public var fat: Double?
    /** Calories of the Fruit (per 100g) in gramm. */
    public var calories: Double?
    /** Sugar of the Fruit (per 100g) in gramm. */
    public var sugar: Double?

    public init(carbohydrates: Double? = nil, protein: Double? = nil, fat: Double? = nil, calories: Double? = nil, sugar: Double? = nil) {
        self.carbohydrates = carbohydrates
        self.protein = protein
        self.fat = fat
        self.calories = calories
        self.sugar = sugar
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case carbohydrates
        case protein
        case fat
        case calories
        case sugar
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(carbohydrates, forKey: .carbohydrates)
        try container.encodeIfPresent(protein, forKey: .protein)
        try container.encodeIfPresent(fat, forKey: .fat)
        try container.encodeIfPresent(calories, forKey: .calories)
        try container.encodeIfPresent(sugar, forKey: .sugar)
    }
}

