//
// Fruits.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Fruits: Codable, JSONEncodable, Hashable, Identifiable {

    /** Genus of the Fruit. */
    public var genus: String
    /** Name of the Fruit. */
    public var name: String
    /** ID of the Fruit. */
    public var id: Int
    /** Family of the Fruit. */
    public var family: String
    /** Order of the Fruit. */
    public var order: String?
    public var nutritions: Nutritions?

    public init(genus: String, name: String, id: Int, family: String, order: String? = nil, nutritions: Nutritions? = nil) {
        self.genus = genus
        self.name = name
        self.id = id
        self.family = family
        self.order = order
        self.nutritions = nutritions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case genus
        case name
        case id
        case family
        case order
        case nutritions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(genus, forKey: .genus)
        try container.encode(name, forKey: .name)
        try container.encode(id, forKey: .id)
        try container.encode(family, forKey: .family)
        try container.encodeIfPresent(order, forKey: .order)
        try container.encodeIfPresent(nutritions, forKey: .nutritions)
    }
}

